'use client';
import { Inter } from 'next/font/google';
import '../globals.css';

import { usePathname } from 'next/navigation';
import DashPage from './page';

import { SidebarProvider } from '@/components/ui/sidebar';
import { AppSidebar } from '@/components/app-sidebar';
import { Button } from '@/components/ui/button';

import { Package, LayoutDashboard, ShoppingCart } from 'lucide-react';
import { useState } from 'react';

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
});

/* export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}; */

export default function Layout({ children }: { children: React.ReactNode }) {
  const [activeButton, setActiveButton] = useState(1);

  const pathname = usePathname();

  const isMainDashboardPage = pathname === '/dash';

  const mainDashboardPageProps = { id: activeButton };

  return (
    <html lang="en" className={inter.className}>
      <body>
        <SidebarProvider>
          <AppSidebar />
          <main className="min-h-screen w-full">
            <div className="flex gap-4 w-full col-span-full h-[65px] items-center p-4 border-b fixed top-0 bg-white">
              <Button variant={activeButton === 1 ? 'outline' : 'ghost'} onClick={() => setActiveButton(1)}>
                <LayoutDashboard /> Overview
              </Button>
              <Button variant={activeButton === 2 ? 'outline' : 'ghost'} onClick={() => setActiveButton(2)}>
                <Package /> Products
              </Button>
              <Button variant={activeButton === 3 ? 'outline' : 'ghost'} onClick={() => setActiveButton(3)}>
                <ShoppingCart /> Orders
              </Button>
            </div>

            {isMainDashboardPage && <DashPage {...mainDashboardPageProps} />}

            {children}
          </main>
        </SidebarProvider>
      </body>
    </html>
  );
}
