'use client';
import '@/app/globals.css';

import { usePathname } from 'next/navigation';
import DashPage from './page';

import { Button } from '@/components/ui/button';

import { Package, LayoutDashboard, ShoppingCart } from 'lucide-react';
import { useState } from 'react';

/* export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}; */

const buttons = (activeButton: number, setActiveButton: React.Dispatch<React.SetStateAction<number>>) => {
  return (
    <div>
      <Button variant={activeButton === 1 ? 'outline' : 'ghost'} onClick={() => setActiveButton(1)}>
        <LayoutDashboard /> Overview
      </Button>
      <Button variant={activeButton === 2 ? 'outline' : 'ghost'} onClick={() => setActiveButton(2)}>
        <Package /> Products
      </Button>
      <Button variant={activeButton === 3 ? 'outline' : 'ghost'} onClick={() => setActiveButton(3)}>
        <ShoppingCart /> Orders
      </Button>
    </div>
  );
};

export default function Layout({ children }: { children: React.ReactNode }) {
  const [activeButton, setActiveButton] = useState(1);

  const pathname = usePathname();

  const isFreelancerDashboardPage = pathname === '/dashboard/freelancer';
  const freelancerDashboardPageProps = { id: activeButton };

  return (
    <main>
      <main className="min-h-screen w-full">
        <div className="flex gap-4 w-full col-span-full h-[65px] items-center p-4 border-b fixed top-0 bg-sidebar">
          {isFreelancerDashboardPage && buttons(activeButton, setActiveButton)}
        </div>

        {isFreelancerDashboardPage && <DashPage {...freelancerDashboardPageProps} />}

        {children}
      </main>
    </main>
  );
}
